### ISSUE TITLE
API endpoint for Family Reducer

### ISSUE THREAD

**Issue by TB-RGB** [TB-RGB/Parentul#9]
## queryText example

```sql
SELECT
	users.first_name AS parent_first_name,
	users.last_name AS parent_last_name,
	json_agg(json_build_object(
		'id', children.id,
		'name', children.name,
		'dob', children.dob
		)) AS children
FROM
	children
JOIN
	users
ON
	children.user_id = users.id
WHERE
	users.id = 1
GROUP BY
	users.id, users.first_name, users.last_name;

**Comment by TB-RGB** [comment]
`FETCH_FAMILY`
`SET_FAMILY`
`UNSET_FAMILY`

**Comment by TB-RGB** [comment]
Family Reducer will be:
 - first_name, last_name from user table; 
 - all children data (name, dob) for the corresponding user (parent) from children table;

{first: first_name, last: last_name, children: [] }

**Comment by TB-RGB** [comment]
-Work on features for the family reducer

-Add a state and create a new branch to work on the feature

**Comment by TB-RGB** [comment]
## Process

`FETCH_FAMILY` will be the type dispatched to the fetchFamily saga that will be your axios.get call
- Need to write query that joins user table and children table, place this on `children.router.js`
---

`SET_FAMILY`
- will be action to update reducer with response from fetch (result.rows)
---
`UNSET_FAMILY` 
- will be action to clear family reducer upon logout

**Comment by asubbarao450** [comment]
![Image](https://github.com/user-attachments/assets/532a2f10-454e-460e-ad30-51e2d0ec9ab7)
